# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: scotteverson
service: auth-server

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  timeout: 30
  environment: 
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token
          method: get